Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 1085, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 551, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 846, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 748, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#general os
import os
import zipfile
import urllib.request

#general plotting
from matplotlib import pyplot as plt

params={'legend.fontsize':'18','axes.labelsize':'18',
        'axes.titlesize':'18','xtick.labelsize':'18',
        'ytick.labelsize':'18','lines.linewidth':2,'axes.linewidth':2,'animation.html': 'html5'}
plt.rcParams.update(params)
plt.rcParams.update({'figure.max_open_warning': 0})

#table/math handling
import pandas as pd
import numpy as np
np.seterr(all='ignore')  # hides irrelevant warnings about divide-by-zero, etc

#astropy
import astropy
import astropy.units as u
from astropy.table import QTable
from astropy.io import fits,ascii
from astropy.nddata import StdDevUncertainty
from astropy.modeling import models
from astropy.visualization import quantity_support
from astropy import constants as const

#specutils
import specutils
from specutils import Spectrum1D, SpectralRegion
from specutils.manipulation import gaussian_smooth
from specutils.fitting import fit_generic_continuum
from specutils.fitting import find_lines_derivative
from specutils.fitting import find_lines_threshold
from specutils.fitting import fit_lines
from specutils.manipulation import noise_region_uncertainty
from specutils.analysis import centroid
from specutils.analysis import line_flux
from specutils.analysis import equivalent_width
from specutils.analysis import template_comparison

quantity_support();  # auto-recognizes units on matplotlib plots
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<module>[0;34m[0m
[1;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01murllib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mrequest[39;00m
[1;32m      6[0m [38;5;66;03m#general plotting[39;00m
[0;32m----> 7[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m [38;5;28;01mimport[39;00m pyplot [38;5;28;01mas[39;00m plt
[1;32m      9[0m params[38;5;241m=[39m{[38;5;124m'[39m[38;5;124mlegend.fontsize[39m[38;5;124m'[39m:[38;5;124m'[39m[38;5;124m18[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124maxes.labelsize[39m[38;5;124m'[39m:[38;5;124m'[39m[38;5;124m18[39m[38;5;124m'[39m,
[1;32m     10[0m         [38;5;124m'[39m[38;5;124maxes.titlesize[39m[38;5;124m'[39m:[38;5;124m'[39m[38;5;124m18[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mxtick.labelsize[39m[38;5;124m'[39m:[38;5;124m'[39m[38;5;124m18[39m[38;5;124m'[39m,
[1;32m     11[0m         [38;5;124m'[39m[38;5;124mytick.labelsize[39m[38;5;124m'[39m:[38;5;124m'[39m[38;5;124m18[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mlines.linewidth[39m[38;5;124m'[39m:[38;5;241m2[39m,[38;5;124m'[39m[38;5;124maxes.linewidth[39m[38;5;124m'[39m:[38;5;241m2[39m,[38;5;124m'[39m[38;5;124manimation.html[39m[38;5;124m'[39m: [38;5;124m'[39m[38;5;124mhtml5[39m[38;5;124m'[39m}
[1;32m     12[0m plt[38;5;241m.[39mrcParams[38;5;241m.[39mupdate(params)

[0;31mModuleNotFoundError[0m: No module named 'matplotlib'
ModuleNotFoundError: No module named 'matplotlib'

